### ISSUE TITLE
rubygems deprecation warnings

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes-deprecated#189]
With the new baseline and the new rubygems version we got a ton of deprecation warnings when installing gems, although it still works (after applying a patch that hopefully will be merged soon). 

Unluckily most of those deprecation warnings say that they are deprecated without a replacement, so getting rid of them will include quite a bit of research and possibly refactoring.

I'll try to tackle this, but no promises made. Shouldn't be a release blocker for 3.2.

**Comment by mpapis** [comment]
I thought  I fixed everything 9c23f10a5ab5d and 58fd5b6a38de give me gists of the errors and I will fix them (hopefully)

**Comment by PragTob** [comment]
Then we definitely duplicated some work from [my commit](https://github.com/ashbb/shoes/commit/c7cbcb5f963e74857e88ae53e85e716498ee0e73) - too bad. I used the build in download reporter from RubyGems that does nothing instead of writing my own one.

Didn't know that anyone worked on them so they might as well be fixed, will try tomorrow to be sure but I guess then they are fixed. Thanks for your work!

**Comment by mpapis** [comment]
yeah i could not resist to fix when I saw the warnings

btw https://github.com/shoes/shoes/blob/develop/lib/shoes/setup.rb#L108 ;)

**Comment by PragTob** [comment]
Yeah already saw all the discussion about bundler etc :-) Btw. thanks for working on RVM - I love it!

Deprecation warnings are fixed, sometime we should adjust the samples since they still throw deprecation warnings but that's not the most important thing. Thank you for your work!
